name: Call Cron API on Deploy

on:
  push:
    branches:
      - main   # 👈 jis branch se Vercel deploy hota hai

jobs:
  call-cron-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call /api/cron after deploy
        run: |
          curl -X POST https://pharmato-nextjs.vercel.app/api/cron
