name: Call Cron API (Every Minutes)

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:   # optional (manual run ke liye)

jobs:
  call-cron-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call /api/cron
        run: |
          curl -X POST https://pharmato-nextjs.vercel.app/api/cron
